name: Deploy BE to Production

on:
  # Runs on pushes targeting production branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allows one concurrent deployment to prod.
concurrency:
  group: "api-prod"
  cancel-in-progress: false

# Calls reusable workflow, passing in the name of the active environment.
jobs:
  build-deploy-dev:
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
    with:
      environment: production